# Generated by Django 4.2.7 on 2025-09-19 23:11

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('skills', models.JSONField(default=list, help_text='List of skills with proficiency levels')),
                ('experience', models.JSONField(default=list, help_text='Work experience data')),
                ('education', models.JSONField(default=list, help_text='Education background')),
                ('certifications', models.JSONField(default=list, help_text='Professional certifications')),
                ('resume_versions', models.JSONField(default=dict, help_text='Different resume versions')),
                ('ai_personality_prompt', models.TextField(default="You are a helpful AI assistant representing this developer's portfolio.", help_text='Prompt that defines AI personality for responses')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'core_profile',
            },
        ),
    ]
