# Generated by Django 4.2.7 on 2025-09-19 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('browser', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('edge', 'Edge'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('page_views_count', models.PositiveIntegerField(default=0)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'db_table': 'visitors_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('chat_start', 'Chat Started'), ('chat_message', 'Chat Message'), ('job_analysis', 'Job Analysis'), ('project_view', 'Project View'), ('download', 'Download'), ('contact', 'Contact')], max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional interaction details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='visitors.visitorsession')),
            ],
            options={
                'verbose_name': 'Visitor Interaction',
                'verbose_name_plural': 'Visitor Interactions',
                'db_table': 'visitors_interaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_view_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('referrer', models.URLField(blank=True)),
                ('time_on_page', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='visitors.visitorsession')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'visitors_pageview',
                'ordering': ['-created_at'],
            },
        ),
    ]
